import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { discoverApplicableFiles } from "../file-discovery.js";

const temporaryDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })));
});

describe("discoverApplicableFiles", () => {
  test("filters applicable files, classifies prompt type, and attaches closest Keys contents", async () => {
    const rootDir = await createFixtureDirectory();

    await writeJavaFile(rootDir, "src/main/java/com/acme/tables/Keys.java", "public class Keys {\nPRIMARY_KEY\n}\n");
    await writeJavaFile(
      rootDir,
      "src/main/java/com/acme/tables/Users.java",
      "This class is generated by jOOQ\nextends TableImpl\norg.jooq\nTables\n",
    );
    await writeJavaFile(
      rootDir,
      "src/main/java/com/acme/repository/UserRepository.java",
      "org.jooq\nTables\nselectFrom(Tables.USERS)\n",
    );
    await writeJavaFile(rootDir, "src/main/java/com/acme/tables/Indexes.java", "org.jooq\npublic class Indexes\n");
    await writeJavaFile(rootDir, "src/main/java/module-info.java", "org.jooq\n");

    const discovery = await discoverApplicableFiles(rootDir);

    expect(discovery.allJavaFiles).toHaveLength(5);
    expect(discovery.candidates.map((candidate) => candidate.relativePath)).toEqual([
      "src/main/java/com/acme/repository/UserRepository.java",
      "src/main/java/com/acme/tables/Users.java",
    ]);

    const repositoryFile = discovery.candidates[0];
    expect(repositoryFile.promptType).toBe("dml-dql");
    expect(repositoryFile.closestKeysContents).toContain("PRIMARY_KEY");

    const ddlFile = discovery.candidates[1];
    expect(ddlFile.promptType).toBe("ddl");
    expect(ddlFile.closestKeysContents).toContain("PRIMARY_KEY");
  });

  test("uses empty Keys contents when no matching Keys file exists", async () => {
    const rootDir = await createFixtureDirectory();

    await writeJavaFile(
      rootDir,
      "src/main/java/com/acme/repository/OrderRepository.java",
      "org.jooq\ntables\nfetch(Tables.ORDERS)\n",
    );

    const discovery = await discoverApplicableFiles(rootDir);

    expect(discovery.candidates).toHaveLength(1);
    expect(discovery.candidates[0]?.closestKeysContents).toBe("");
  });

  test("preserves UTF-8 source contents without latin1 mojibake", async () => {
    const rootDir = await createFixtureDirectory();

    await writeJavaFile(rootDir, "src/main/java/com/acme/tables/Keys.java", "public class Keys {\nPRIMARY_KEY\n}\n");
    await writeJavaFile(
      rootDir,
      "src/main/java/com/acme/tables/Users.java",
      'This class is generated by jOOQ\nextends TableImpl\norg.jooq\nTables\ncreateField(DSL.name("id"), SQLDataType.BIGINT, this, "主键（用户id）");\n',
      "utf8",
    );

    const discovery = await discoverApplicableFiles(rootDir);

    expect(discovery.candidates).toHaveLength(1);
    expect(discovery.candidates[0]?.contents).toContain("主键（用户id）");
    expect(discovery.candidates[0]?.contents).not.toContain("ä¸»");
  });
});

async function createFixtureDirectory(): Promise<string> {
  const directory = await mkdtemp(path.join(os.tmpdir(), "detecty-thingy-"));
  temporaryDirectories.push(directory);
  return directory;
}

async function writeJavaFile(
  rootDir: string,
  relativePath: string,
  contents: string,
  encoding: BufferEncoding = "latin1",
): Promise<void> {
  const absolutePath = path.join(rootDir, relativePath);
  await mkdir(path.dirname(absolutePath), { recursive: true });
  await writeFile(absolutePath, contents, encoding);
}
