import { readFile } from "node:fs/promises";
import path from "node:path";

import fg from "fast-glob";
import pLimit from "p-limit";

const excludedPathFragments = [
  "module-info.java",
  "package-info.java",
  "information_schema/InformationSchema.java",
  "information_schema/tables",
  "mysql/Mysql.java",
  "mysql/tables",
  "performance_schema/PerformanceSchema.java",
  "performance_schema/tables",
  "sys/Sys.java",
  "sys/tables",
  "FlywaySchemaHistory.java",
  "Databasechangelog.java",
  "Databasechangeloglock.java",
  "information_schema/Domains.java",
  "pg_catalog/PgCatalog.java",
  "pg_catalog/tables",
  "tables/Qrtz",
  "PgpArmorHeaders.java",
  "tables/Dblink",
  "tables/Each.java",
  "tables/Skeys.java",
  "tables/Svals.java",
];

const includedPhrases = ["org.jooq", "Tables", "tables"];

const excludedPhrases = [
  "extends TableRecordImpl",
  "extends UpdatableRecordImpl",
  "extends org.jooq.impl.UpdatableRecordImpl",
  "extends CatalogImpl",
  "extends SchemaImpl",
  "extends UDTImpl",
  "extends UDTRecordImpl",
  "extends DAOImpl",
  "extends AbstractRoutine",
  "implements EnumType",
  "implements DeserializableJooqEnum",
  "public class Indexes",
  "public class Keys",
  "public class Routines",
  "public class Sequences",
  "public class Tables",
  "public class Domains",
  "class AbstractSpringDAOImpl",
  "extends AbstractSpringDAOImpl",
  "tables.pojos;",
  "tables.interfaces;",
  "Targeted by JavaCPP",
];

const ddlIndicatorPhrases = ["This class is generated by jOOQ", "extends TableImpl", "extends org.jooq.impl.TableImpl"];

const latin1Decoder = new TextDecoder("latin1");
const fileReadLimit = pLimit(32);

type LoadedJavaFile = {
  absolutePath: string;
  relativePath: string;
  contents: string;
};

export type FileCandidate = {
  absolutePath: string;
  relativePath: string;
  contents: string;
  promptType: "ddl" | "dml-dql";
  closestKeysContents: string;
};

export type DiscoveryResult = {
  allJavaFiles: string[];
  candidates: FileCandidate[];
};

export async function discoverApplicableFiles(rootDir: string): Promise<DiscoveryResult> {
  const files = await loadJavaFiles(rootDir);
  const keysFiles = files.filter((file) => file.contents.includes("public class Keys "));

  const candidates = files.filter(isApplicableFile).map((file) => {
    const closestKeysFile = findClosestKeysFile(file, keysFiles);
    const promptType: FileCandidate["promptType"] = ddlIndicatorPhrases.some((phrase) => file.contents.includes(phrase))
      ? "ddl"
      : "dml-dql";

    return {
      absolutePath: file.absolutePath,
      relativePath: file.relativePath,
      contents: file.contents,
      promptType,
      closestKeysContents: closestKeysFile?.contents ?? "",
    };
  });

  return {
    allJavaFiles: files.map((file) => file.absolutePath),
    candidates,
  };
}

async function loadJavaFiles(rootDir: string): Promise<LoadedJavaFile[]> {
  const relativePaths = await fg("**/*.java", {
    cwd: rootDir,
    onlyFiles: true,
    dot: false,
    followSymbolicLinks: false,
  });

  const sortedRelativePaths = relativePaths.map(normalizePath).sort();

  return Promise.all(
    sortedRelativePaths.map((relativePath) =>
      fileReadLimit(async () => ({
        absolutePath: path.join(rootDir, relativePath),
        relativePath,
        contents: await readLatin1File(path.join(rootDir, relativePath)),
      })),
    ),
  );
}

function isApplicableFile(file: LoadedJavaFile): boolean {
  if (excludedPathFragments.some((fragment) => file.relativePath.includes(fragment))) {
    return false;
  }

  if (!includedPhrases.some((phrase) => file.contents.includes(phrase))) {
    return false;
  }

  if (excludedPhrases.some((phrase) => file.contents.includes(phrase))) {
    return false;
  }

  return true;
}

function findClosestKeysFile(file: LoadedJavaFile, keysFiles: LoadedJavaFile[]): LoadedJavaFile | undefined {
  let closest: LoadedJavaFile | undefined;
  let closestCommonPrefixLength = -1;

  for (const keysFile of keysFiles) {
    const prefixLength = commonPrefixLength(file.relativePath, keysFile.relativePath);
    if (prefixLength > closestCommonPrefixLength) {
      closest = keysFile;
      closestCommonPrefixLength = prefixLength;
    }
  }

  return closest;
}

function commonPrefixLength(left: string, right: string): number {
  const max = Math.min(left.length, right.length);
  let index = 0;

  while (index < max && left[index] === right[index]) {
    index += 1;
  }

  return index;
}

async function readLatin1File(filePath: string): Promise<string> {
  const buffer = await readFile(filePath);
  return latin1Decoder.decode(buffer);
}

function normalizePath(inputPath: string): string {
  return inputPath.split(path.sep).join("/");
}
