import { readdir, readFile } from "node:fs/promises";
import path from "node:path";

const excludedPathFragments = [
  "module-info.java",
  "package-info.java",
  "information_schema/InformationSchema.java",
  "information_schema/tables",
  "mysql/Mysql.java",
  "mysql/tables",
  "performance_schema/PerformanceSchema.java",
  "performance_schema/tables",
  "sys/Sys.java",
  "sys/tables",
  "FlywaySchemaHistory.java",
  "Databasechangelog.java",
  "Databasechangeloglock.java",
  "information_schema/Domains.java",
  "pg_catalog/PgCatalog.java",
  "pg_catalog/tables",
  "tables/Qrtz",
  "PgpArmorHeaders.java",
  "tables/Dblink",
  "tables/Each.java",
  "tables/Skeys.java",
  "tables/Svals.java",
];

const includedPhrases = [
  "org.jooq",
  "Tables",
  "tables",
];

const excludedPhrases = [
  "extends TableRecordImpl",
  "extends UpdatableRecordImpl",
  "extends org.jooq.impl.UpdatableRecordImpl",
  "extends CatalogImpl",
  "extends SchemaImpl",
  "extends UDTImpl",
  "extends UDTRecordImpl",
  "extends DAOImpl",
  "extends AbstractRoutine",
  "implements EnumType",
  "implements DeserializableJooqEnum",
  "public class Indexes",
  "public class Keys",
  "public class Routines",
  "public class Sequences",
  "public class Tables",
  "public class Domains",
  "class AbstractSpringDAOImpl",
  "extends AbstractSpringDAOImpl",
  "tables.pojos;",
  "tables.interfaces;",
  "Targeted by JavaCPP",
];

const ddlIndicatorPhrases = [
  "This class is generated by jOOQ",
  "extends TableImpl",
  "extends org.jooq.impl.TableImpl",
];

const latin1Decoder = new TextDecoder("latin1");

export type FileCandidate = {
  absolutePath: string;
  relativePath: string;
  contents: string;
  promptType: "ddl" | "dml-dql";
  closestKeysContents: string;
};

export type DiscoveryResult = {
  allJavaFiles: string[];
  candidates: FileCandidate[];
};

export async function discoverApplicableFiles(rootDir: string): Promise<DiscoveryResult> {
  const allJavaFiles = await walkJavaFiles(rootDir);
  const keysFiles = await collectKeysFiles(allJavaFiles);

  const candidates: FileCandidate[] = [];

  for (const absolutePath of allJavaFiles) {
    const relativePath = normalizePath(path.relative(rootDir, absolutePath));
    if (excludedPathFragments.some((fragment) => relativePath.includes(fragment))) {
      continue;
    }

    const contents = await readLatin1File(absolutePath);
    if (!includedPhrases.some((phrase) => contents.includes(phrase))) {
      continue;
    }

    if (excludedPhrases.some((phrase) => contents.includes(phrase))) {
      continue;
    }

    const closestKeysPath = findClosestKeysFile(absolutePath, keysFiles);
    const closestKeysContents = closestKeysPath ? await readLatin1File(closestKeysPath) : "";
    const promptType = ddlIndicatorPhrases.some((phrase) => contents.includes(phrase))
      ? "ddl"
      : "dml-dql";

    candidates.push({
      absolutePath,
      relativePath,
      contents,
      promptType,
      closestKeysContents,
    });
  }

  return { allJavaFiles, candidates };
}

async function walkJavaFiles(rootDir: string): Promise<string[]> {
  const results: string[] = [];
  const queue = [rootDir];

  while (queue.length > 0) {
    const currentDir = queue.pop();
    if (!currentDir) {
      continue;
    }

    const entries = await readdir(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const absolutePath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        queue.push(absolutePath);
        continue;
      }

      if (entry.isFile() && entry.name.endsWith(".java")) {
        results.push(absolutePath);
      }
    }
  }

  return results.sort();
}

async function collectKeysFiles(allJavaFiles: string[]): Promise<string[]> {
  const matches: string[] = [];

  for (const filePath of allJavaFiles) {
    const contents = await readLatin1File(filePath);
    if (contents.includes("public class Keys ")) {
      matches.push(filePath);
    }
  }

  return matches;
}

function findClosestKeysFile(filePath: string, keysFiles: string[]): string | undefined {
  let closest: string | undefined;
  let closestCommonPrefixLength = -1;

  for (const keysFilePath of keysFiles) {
    const prefixLength = commonPrefixLength(filePath, keysFilePath);
    if (prefixLength > closestCommonPrefixLength) {
      closest = keysFilePath;
      closestCommonPrefixLength = prefixLength;
    }
  }

  return closest;
}

function commonPrefixLength(left: string, right: string): number {
  const max = Math.min(left.length, right.length);
  let index = 0;

  while (index < max && left[index] === right[index]) {
    index += 1;
  }

  return index;
}

async function readLatin1File(filePath: string): Promise<string> {
  const buffer = await readFile(filePath);
  return latin1Decoder.decode(buffer);
}

function normalizePath(inputPath: string): string {
  return inputPath.split(path.sep).join("/");
}
